TYPO3:
  Jobqueue:
    Rabbitmq:
      testing:
        # Set to TRUE to enable functional testing against a rabbitmq server
        enabled: TRUE
          client:
            host: '127.0.0.1'
            port: '5672'
            username: 'guest'
            password: 'guest'
            vhost: '/'
